databases:
  - name: metaproject
    databaseName: metaproject
    user: metaproject

services:
  - type: web
    name: metaproject
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn metaproject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: metaproject
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4