# Generated by Django 3.2.6 on 2022-12-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.CharField(default='', max_length=50)),
                ('heroID', models.IntegerField(default=0)),
                ('item', models.CharField(default='', max_length=50)),
                ('itemID', models.IntegerField(default=0)),
                ('winrate', models.CharField(default='', max_length=50)),
                ('usage', models.CharField(default='', max_length=50)),
                ('queryTime', models.CharField(default='', max_length=50)),
                ('totalMatches', models.IntegerField(default=0)),
            ],
        ),
    ]
